### ISSUE TITLE
ReferenceError with Gulp 4

### ISSUE THREAD

**Issue by Freyert** [yuanqing/gulp-tape#1]
I get a `ReferenceError` when using gulp 4. And the only feedback I'm getting is: `it is not defined`.

``` javascript
var gulp = require('gulp');
var tape = require('gulp-tape');

gulp.task('test', function() {
  return gulp.src('test/*.js')
  .pipe(tape());
});
```

**Comment by yuanqing** [comment]
@Freyert, I can't seem to reproduce this issue.

This is my `package.json`:

``` json
{
  "devDependencies": {
    "gulp": "gulpjs/gulp#4.0",
    "gulp-tape": "0.0.1",
    "tape": "^4.2.0"
  },
  "scripts": {
    "test": "gulp test"
  }
}
```

And a test file `test/index.js`:

``` js
var test = require('tape');

test('foo', function(t) {
  t.plan(1);
  t.ok(true);
});
```

Doing `npm install` followed by an `npm test` works as expected for me.

**Comment by Freyert** [comment]
What does your gulp file look like? Ok, that's weird. It worked this time.

**Comment by yuanqing** [comment]
My Gulp file is the same as the one you had in your initial comment
