### ISSUE TITLE
Better tests

### ISSUE THREAD

**Issue by yuanqing** [yuanqing/gulp-tape#12]
We need more comprehensive tests to verify that this module works for the following:
- The &ldquo;typical&rdquo; use case of running `test/*.js`
  - TAP output should be consistent with Tape; output must include the results summary
  - A failing Tape test should cause Gulp to error out
- Running tests on file changes via Gulp&rsquo;s `watch` &mdash; see **https://github.com/yuanqing/gulp-tape/issues/10**
- Generating correct test coverage with [`gulp-istanbul`](https://github.com/SBoudrias/gulp-istanbul)

**Comment by zoubin** [comment]
I'd like to add some tests for `watch`.
