### ISSUE TITLE
Option to specify alternative modifications of tape

### ISSUE THREAD

**Issue by 11bit** [yuanqing/gulp-tape#14]
I want to use gulp-tape to run blue-tape tests. But as I see currently it is not possible because tape is explicitly required in gulp-tape's source. 

What to you think regarding an optional way to specify tape analogues via an in API? Something like this: 

```
.pipe(tape({
  tape: require('blue-tape')
}));
```

**Comment by zoubin** [comment]
Try to `require('blue-tape')` before you `require('gulp-tape')`

**Comment by 11bit** [comment]
Hm, what really helped is to install `blue-tape` after `gulp-tape`. In opposite case `blue-tape` installs it's own `tape` which breaks some `gulp-tape` features like reporters. 

So `npm i blue-tape gulp-tape` doesn't work. But if one removes node_modules and installs them again it will work. 

How do you think what is the best way to fix it?

**Comment by zoubin** [comment]
`tape` is put in `peerDependencies` of `gulp-tape`.
So, `npm i --save-dev blue-tape gulp-tape tape` should work.
`gulp-tape` and `blue-tape` would `require` the same `tape`.

``` javascript
gulp.task('test', function () {
  require('blue-tape')
  var tape = require('gulp-tape')
  return gulp.src('test/*.js')
     .pipe(tape(opts))
})

```

test/*.js:

``` javascript
var test = require('tape')

test('test', function (t) {
})
```

**Comment by 11bit** [comment]
Thanks for clearing things out. I didn't install tape as a separate dependency and relied on fact that npm 2.\* automatically installs it for me. This somehow worked not as expected

`npm i --save-dev blue-tape gulp-tape` #Doesn't work
`npm i --save-dev blue-tape gulp-tape tape` #Work
