### ISSUE TITLE
Can't Forward Changes from Babel into Gulp Tape

### ISSUE THREAD

**Issue by dwighthouse** [yuanqing/gulp-tape#27]
## Issue

I use various plugins to remap relative path names for require'd files to use. When running tape directly via CLI, this works. When running babel and tape via gulp-babel and gulp-tape, respectively, this doesn't work. It's as if gulp-babel never runs as far as gulp-tape is concerned, but I have confirmed separately that gulp-babel runs by outputting its results rather than piping them into gulp-tape.

Specifically, I added a gulp-babel step prior to the gulp-tape step in the gulp stream:

```
    ...
    .src('fixtures/test.js')
    .pipe(babel({presets: ['env']}))
    .pipe(
      tape({...
```

Using this .babelrc file to do path resolution based off a known additional root folder:

```
{
  "plugins": [
    ["module-resolver", {
      "root": ["./fixtures"]
    }]
  ]
}
```

## To Reproduce

Go to the fork I have created: https://github.com/dwighthouse/gulp-tape

Clone the repository and cd into the test directory and run this command:

```
node ../node_modules/tape/bin/tape -r babel-register fixtures/test.js
```

This will produce the output:

```
!!! successfully imported deep_test using babel-transformed root paths 43
TAP version 13
# foo
ok 1 should be equal

1..1
# tests 1
# pass  1

# ok
```

That is the expected output.

Now, if the same sequence is run via gulp:

```
gulp test
```

The resulting output fails due to inability to locate the files using transformed paths:

```
[16:38:21] Using gulpfile /ROOT/gulp-tape/test/gulpfile.js
[16:38:21] Starting 'test'...
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |    44.44 |      100 |        0 |    44.44 |                   |
 index.js |       50 |      100 |        0 |       50 |                 2 |
 test.js  |    42.86 |      100 |        0 |    42.86 |          6,8,9,10 |
----------|----------|----------|----------|----------|-------------------|
1..0 # no tests found
[16:38:22] Finished 'test' after 784 ms
[16:38:22] Command failed: /ROOT/gulp-tape/node_modules/nyc/bin/nyc.js /ROOT/gulp-tape/node_modules/tape/bin/tape /ROOT/gulp-tape/test/fixtures/test.js
module.js:487
    throw err;
    ^

Error: Cannot find module 'deep/deep_test'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/ROOT/gulp-tape/test/fixtures/test.js:2:39)
    at Module._compile (module.js:569:30)
    at Module.replacementCompile (/ROOT/gulp-tape/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/ROOT/gulp-tape/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/ROOT/gulp-tape/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:503:32)
```

See the changes necessary to see the issue specifically:

https://github.com/dwighthouse/gulp-tape/pull/1/files

**Comment by dwighthouse** [comment]
Experimenting with the source code, it looks like the issue is due to gulp-tape taking the file paths from the stream, rather than the file contents, and then executing tape directly on the paths. Obviously, the paths will have none of the transforms performed by previous gulp plugins.

I have found a partial workaround by passing in the -r argument to gulp-tape, like so:

```javascript
tape({
    bail: true,
    nyc: true,
    r: 'babel-register'
})
```

However, this method is sub-optimal, as it requires a .babelrc file in place with the appropriate actions. If .babelrc is needed in a different form for other parts of the build system, this can conflict.

A more complete solution is to use babel-register's API in a custom local module, and then require that with the -r syntax:

```javascript
tape({
    bail: true,
    nyc: true,
    r: './babel-register-test'
})
```

Where there is a local file babel-register-test.js that contains:

```javascript
require("babel-register")({
    "plugins": [
        ["module-resolver", { "root": ["./fixtures"] }]
    ]
});
```

This is still not as good as allowing the file's contents to be passed to tape, rather than paths. It looks like tape-run ( https://github.com/juliangruber/tape-run ) might do this.

**Comment by yuanqing** [comment]
@dwighthouse Thank you for reporting this.

1. Use of the `require` (or `r`) option is [documented behaviour](https://github.com/yuanqing/gulp-tape#tapeoptions) for the `gulp-tape` module.

2. I think that the solution you proposed — of pointing to a local file with all the necessary configuration — is a simple and clean one.

    > allowing the file's contents to be passed to tape, rather than paths

    This seems to be a non-trivial change. Happy to take a PR that would enable this!
